services:
  flowise-local:
    container_name: flowise-local
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3005:80"
    volumes:
      - ~/.flowise:/root/.flowise